services:
  db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: zemi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zemi-evaluation
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local
